"""
Django settings for plina project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured

from plina.env import (bool_from_env, database_from_env, list_from_env, oidc_from_env, origins_from_env,
                       secret_from_env)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Development settings unless the environment says otherwise; the Docker
# image runs with DEBUG=False (README: Deployment with Docker).
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool_from_env('DEBUG', default=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_from_env('SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'Set SECRET_KEY (or SECRET_KEY_FILE) when DEBUG is off; README: Deployment with Docker.')
    SECRET_KEY = 'django-insecure-ji(%q7xuu4=^#f33(uu6q1dx9f&f^fqjp^=vy^3@$*2&(+van*'

# The host names Plina is reached under, comma-separated (e.g. plina.example.com).
ALLOWED_HOSTS = list_from_env('ALLOWED_HOSTS', default=[])
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'Set ALLOWED_HOSTS to the host name(s) Plina is reached under, e.g. plina.example.com.')

# Behind a reverse proxy that terminates TLS and says so in X-Forwarded-Proto
# (nginx passes it on); cookies only over HTTPS in production.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE = bool_from_env('SECURE_COOKIES', default=not DEBUG)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'tasks.apps.TasksConfig',
    'accounts.apps.AccountsConfig',
]

MIDDLEWARE = [
    'plina.health.HealthCheckMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Queries see only the logged-in user's data (plina.scoping).
    'plina.scoping.OwnerScopeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tasks.middleware.UserTimeZoneMiddleware',
]

ROOT_URLCONF = 'plina.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plina.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# SQLite (db.sqlite3) unless DB_ENGINE, DB_NAME, DB_USER, … say otherwise.
DATABASES = {
    'default': database_from_env(BASE_DIR),
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic puts the admin's files here; in Docker a volume nginx serves.
STATIC_ROOT = BASE_DIR / 'static'
# Uploads (none yet); in Docker a volume nginx serves.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Mail: for "Forgot your password?" (Django's password reset under
# /django/accounts/), offered when EMAIL_HOST is set. Port 587 means STARTTLS,
# 465 TLS, unless EMAIL_USE_TLS / EMAIL_USE_SSL say otherwise.
PASSWORD_RESET_ENABLED = bool(os.environ.get('EMAIL_HOST'))
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT') or 25)
EMAIL_USE_TLS = bool_from_env('EMAIL_USE_TLS', default=EMAIL_PORT == 587)
EMAIL_USE_SSL = bool_from_env('EMAIL_USE_SSL', default=EMAIL_PORT == 465)
EMAIL_HOST_USER = os.environ.get('EMAIL_USER', '')
EMAIL_HOST_PASSWORD = secret_from_env('EMAIL_PASSWORD') or ''
DEFAULT_FROM_EMAIL = SERVER_EMAIL = os.environ.get('EMAIL_FROM') or 'webmaster@localhost'

# Every endpoint needs a logged-in user (README: Accounts), who sees only
# their own data (plina.scoping). The session comes from the login API or
# the single sign-on; changes need the CSRF token (the app sends it).
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['accounts.authentication.SessionAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
}

# Local accounts always (created with createsuperuser or in the admin);
# single sign-on with OpenID Connect when the OIDC_ variables are set
# (plina.env.oidc_from_env: the mozilla-django-oidc settings).
# Django's own pages (the password reset) send you to the app's login page.
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
# A failed single sign-on comes back to the app's login page, which says so.
LOGIN_REDIRECT_URL_FAILURE = '/?login=failed'
globals().update(oidc_from_env())
OIDC_ENABLED = 'OIDC_RP_CLIENT_ID' in globals()
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend'] + (
    ['accounts.oidc.PlinaOIDCBackend'] if OIDC_ENABLED else [])
OIDC_USE_PKCE = True
OIDC_STORE_ID_TOKEN = True  # for logging out at the provider too
OIDC_TIMEOUT = 15

# Everything to stdout/stderr, where `docker compose logs` finds it; errors
# with their traceback (Django would only mail them without DEBUG).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': os.environ.get('LOG_LEVEL', 'INFO')},
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        # 4xx are in the access log; tracebacks of 5xx here.
        'django.request': {'handlers': ['console'], 'level': 'ERROR', 'propagate': False},
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Pages that may call the API: the Vite dev server unless the environment
# variable CORS_ALLOWED_ORIGINS lists others, comma-separated (README) — with
# the session cookie (the login).
CORS_ALLOWED_ORIGINS = origins_from_env("CORS_ALLOWED_ORIGINS", default=[
    "http://localhost:5173",
    "http://127.0.0.1:5173",
])
CORS_ALLOW_CREDENTIALS = True
# Pages on other origins that may make changes (CSRF): those allowed to call
# the API unless CSRF_TRUSTED_ORIGINS says otherwise, e.g.
# https://plina.example.com behind a TLS proxy.
CSRF_TRUSTED_ORIGINS = origins_from_env('CSRF_TRUSTED_ORIGINS', default=CORS_ALLOWED_ORIGINS)
# After the provider, back to the app's page — also on the origins allowed
# to call the API (the Vite dev server during development).
OIDC_REDIRECT_ALLOWED_HOSTS = [urlparse(origin).netloc for origin in CORS_ALLOWED_ORIGINS]
PLANNING_HORIZON_DAYS = 60  # planning window for generated buckets (A9); tune freely
MAX_PLAN_ALTERNATIVES = 4  # chooser cap (A11); expected to be tuned after real-world use
