# Generated by Django 6.0.1 on 2026-01-25 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_color_tag_color_task_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timebucket',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
    ]
