# Generated by Django 6.0.6 on 2026-07-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_fixed_alter_timebucket_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='completed at'),
        ),
    ]
