# Generated by Django 6.0.6 on 2026-07-06 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='tasks.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='tasks.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor'), name='unique_task_dependency'), models.CheckConstraint(condition=models.Q(('predecessor', models.F('successor')), _negated=True), name='no_self_dependency')],
            },
        ),
    ]
