# Generated by Django 6.0.6 on 2026-07-06 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskdependency'),
    ]

    def _clear_time_buckets(apps, schema_editor):
        apps.get_model('tasks', 'TimeBucket').objects.all().delete()

    operations = [
        migrations.RunPython(_clear_time_buckets, migrations.RunPython.noop),
        migrations.AddField(
            model_name='task',
            name='is_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timebucket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
