# Generated by Django 6.0.6 on 2026-07-07 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_is_appointment_alter_timebucket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=512)),
                ('is_accepted', models.BooleanField(default=False)),
                ('feasible', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('buckets_snapshot', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket_key', models.UUIDField(blank=True, default=None, null=True)),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('order', models.PositiveIntegerField()),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_entries', to='tasks.timebucket')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tasks.plan')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='tasks.task')),
            ],
            options={
                'verbose_name_plural': 'plan entries',
                'ordering': ['order'],
            },
        ),
    ]
