# Generated by Django 6.0.6 on 2026-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_trackingsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="timebucket",
            name="origin_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="original occurrence"
            ),
        ),
    ]
