# Generated by Django 6.0.6 on 2026-09-25 17:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_alter_project_description_alter_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_dropped_rest",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_estimate",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_first_estimate",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_subtree_time_spent",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_time_spent",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="tasks.task",
            ),
        ),
        migrations.CreateModel(
            name="TaskEstimateChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "old_duration",
                    models.DurationField(blank=True, default=None, null=True),
                ),
                (
                    "new_duration",
                    models.DurationField(blank=True, default=None, null=True),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("edited", "edited"),
                            ("split", "split"),
                            ("set_to_sum", "set to sum of parts"),
                            ("raised_from_warning", "raised from over-budget warning"),
                            ("migrated", "migrated from a project"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate_changes",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at"],
            },
        ),
    ]
