# Generated by Django 6.0.6 on 2026-09-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_projects_to_task_tree"),
    ]

    operations = [
        migrations.AddField(
            model_name="planentry",
            name="is_rest",
            field=models.BooleanField(default=False),
        ),
    ]
