# Generated by Django 6.0.6 on 2026-09-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_usersettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecttaskitem",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projecttaskitem",
            name="task",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectTaskItem",
        ),
    ]
