# Generated by Django 6.0.6 on 2026-09-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_remove_legacy_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="time_zone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
