# Generated by Django 6.0.6 on 2026-10-02 13:53

from django.db import migrations, models

#: The old default every task got, so it never meant a chosen color.
TEAL = b"\x53\x9d\xad"


def forwards(apps, schema_editor):
    """Tasks with the old default have no color of their own any more
    (subtasks inherit); top-level tasks get distinct automatic colors
    (docs/task-entry-ui.md §4.4)."""
    # A pure function over '#rrggbb' strings; it uses no models.
    from tasks.services.colors import distinct_color
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(color=TEAL).update(color=None)
    used = ["#" + bytes(color).hex() for color in
            Task.objects.filter(completed_at=None).exclude(color=None)
            .values_list("color", flat=True)]
    # Projects that will show it first; those with a chosen color get one
    # too (it is what "Automatic" shows), as in services.colors.
    projects = Task.objects.filter(parent=None).order_by(
        models.F("color").asc(nulls_first=True), "order", "header")
    for task in projects:
        color = distinct_color(used)
        task.auto_color = bytes.fromhex(color[1:])
        task.save(update_fields=["auto_color"])
        used.append(color)


def backwards(apps, schema_editor):
    apps.get_model("tasks", "Task").objects.filter(color=None).update(color=TEAL)


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_user_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="auto_color",
            field=models.BinaryField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="color",
            field=models.BinaryField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.RunPython(forwards, backwards),
    ]
