# Generated by Django 6.0.6 on 2026-10-02 15:07

from django.db import migrations, models

#: The old default every bucket type got, so it never meant a chosen color.
TEAL = b"\x53\x9d\xad"


def forwards(apps, schema_editor):
    """Like tasks (0017): bucket types with the old default have no chosen
    color any more; all get distinct automatic colors (§4.4)."""
    # A pure function over '#rrggbb' strings; it uses no models.
    from tasks.services.colors import distinct_color
    Type = apps.get_model("tasks", "TimeBucketType")
    Type.objects.filter(color=TEAL).update(color=None)
    used = ["#" + bytes(color).hex() for color in
            Type.objects.exclude(color=None).values_list("color", flat=True)]
    for bucket_type in Type.objects.order_by(models.F("color").asc(nulls_first=True), "name", "id"):
        color = distinct_color(used)
        bucket_type.auto_color = bytes.fromhex(color[1:])
        bucket_type.save(update_fields=["auto_color"])
        used.append(color)


def backwards(apps, schema_editor):
    apps.get_model("tasks", "TimeBucketType").objects.filter(color=None).update(color=TEAL)


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_task_auto_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="timebuckettype",
            name="auto_color",
            field=models.BinaryField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="timebuckettype",
            name="color",
            field=models.BinaryField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.RunPython(forwards, backwards),
    ]
