# Generated by Django 6.0.6 on 2026-10-05 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_timebuckettype_auto_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="week_view_end",
            field=models.TimeField(default=datetime.time(16, 45)),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="week_view_start",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
