# Generated by Django 6.0.6 on 2026-10-06 11:35

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_recurring_tasks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="place",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="timebuckettype",
            name="special_end",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="timebuckettype",
            name="special_start",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="CalendarSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=2048)),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                ("hex_color", models.CharField(default="#7986cb", max_length=7)),
                (
                    "last_attempt_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Marker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, default="")),
                ("place", models.CharField(blank=True, default="", max_length=512)),
                ("start", models.DateTimeField()),
                ("duration", models.DurationField(default=datetime.timedelta(days=1))),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="deadline_marker",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deadline_tasks",
                to="tasks.marker",
            ),
        ),
        migrations.CreateModel(
            name="CalendarLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("uid", models.CharField(max_length=512)),
                (
                    "recurrence_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("data", models.JSONField(default=dict)),
                ("owned", models.BooleanField(default=True)),
                ("pending", models.JSONField(blank=True, default=list)),
                ("start", models.DateTimeField()),
                (
                    "bucket_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_links",
                        to="tasks.timebuckettype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_links",
                        to="tasks.task",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="tasks.calendarsubscription",
                    ),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_links",
                        to="tasks.marker",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subscription", "uid", "recurrence_id"),
                        name="one_link_per_event",
                    )
                ],
            },
        ),
    ]
