# Generated by Django 6.0.6 on 2026-10-07 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0022_calendar_markers_special_buckets"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskseries",
            name="calendar_auto",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskseries",
            name="calendar_mismatch",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="taskseries",
            name="calendar_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series",
                to="tasks.calendarsubscription",
            ),
        ),
        migrations.AddField(
            model_name="taskseries",
            name="calendar_uid",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
