# Generated by Django 6.0.6 on 2026-10-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0025_unpin_tracked_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_unplanned",
            field=models.BooleanField(default=False),
        ),
    ]
