# Generated by Django 4.2.4 on 2023-08-27 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(default='')),
                ('priority', models.FloatField(default=5.0)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=1024)),
                ('description', models.TextField(default='')),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='start date')),
                ('duration', models.DurationField(blank=True, default=None, null=True)),
                ('latest_finish_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='due until')),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('priority', models.FloatField(default=5.0)),
                ('tags', models.ManyToManyField(related_name='tasks', to='tasks.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to='tasks.project')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_item', to='tasks.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', to='tasks.tag'),
        ),
    ]
