# Generated by Django 4.2.7 on 2023-11-23 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="color",
            field=models.BinaryField(
                blank=True, default=b"S\x9d\xad", max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.BinaryField(
                blank=True, default=b"S\x9d\xad", max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="color",
            field=models.BinaryField(
                blank=True, default=b"S\x9d\xad", max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="tasks.tag"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tasks.tag"
            ),
        ),
        migrations.CreateModel(
            name="TimeBucketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("color", models.BinaryField(default=b"S\x9d\xad", max_length=3)),
                ("start_times", models.CharField(default="", max_length=512)),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=14400)),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="time_bucket_types", to="tasks.tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            11,
                            23,
                            18,
                            20,
                            52,
                            457474,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="start date",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=14400)),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buckets",
                        to="tasks.timebuckettype",
                    ),
                ),
            ],
        ),
    ]
